org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Set after online deployment, for example:
# receptionQrApiUrl=https://twoj-backend.onrender.com/api/qr/redeem
receptionQrApiUrl=https://receptionqr-api.onrender.com/api/qr/redeem
