from __future__ import annotations

import os
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

BASE_DIR = Path(__file__).resolve().parent
DEFAULT_SQLITE_URL = f"sqlite:///{(BASE_DIR / 'data' / 'reception_qr.sqlite3').as_posix()}"


def resolve_database_url() -> str:
    configured_url = os.getenv("RECEPTIONQR_DATABASE_URL", DEFAULT_SQLITE_URL)

    if configured_url.startswith("postgresql://") and "+psycopg" not in configured_url:
        return configured_url.replace("postgresql://", "postgresql+psycopg://", 1)

    if configured_url.startswith("postgres://"):
        return configured_url.replace("postgres://", "postgresql+psycopg://", 1)

    return configured_url


DATABASE_URL = resolve_database_url()

app = FastAPI(
    title="Reception QR API",
    version="2.0.0",
    description="API do generowania QR po zakończeniu gry i oznaczania ich jako wykorzystane.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

engine: Engine = create_engine(DATABASE_URL, future=True, pool_pre_ping=True)


class IssueQrRequest(BaseModel):
    player_id: str = Field(..., min_length=1, max_length=120)
    points: int = Field(..., ge=0)
    reward_name: str | None = Field(default=None, max_length=255)
    match_id: str | None = Field(default=None, max_length=120)


class RedeemQrRequest(BaseModel):
    code: str = Field(..., min_length=1, max_length=255)
    staff_id: str = Field(default="recepcja_1", min_length=1, max_length=120)


class QrResponse(BaseModel):
    status: str
    message: str
    code: str
    player_id: str | None = None
    points: int | None = None
    reward_name: str | None = None
    match_id: str | None = None
    used_at: str | None = None
    used_by: str | None = None
    scan_count: int | None = None


class IssueQrResponse(BaseModel):
    code: str
    qr_payload: str
    player_id: str
    points: int
    reward_name: str | None = None
    match_id: str | None = None
    issued_at: str


class HealthResponse(BaseModel):
    status: str
    database_url: str
    database_backend: str


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def database_backend_name() -> str:
    return engine.url.get_backend_name()


@contextmanager
def db_transaction() -> Iterator[Any]:
    with engine.begin() as connection:
        yield connection


def initialize_database() -> None:
    if engine.dialect.name == "sqlite":
        qr_codes_ddl = """
        CREATE TABLE IF NOT EXISTS qr_codes (
            code TEXT PRIMARY KEY,
            player_id TEXT NOT NULL,
            match_id TEXT,
            points INTEGER NOT NULL,
            reward_name TEXT,
            status TEXT NOT NULL DEFAULT 'issued',
            issued_at TEXT NOT NULL,
            used_at TEXT,
            used_by TEXT,
            scan_count INTEGER NOT NULL DEFAULT 0
        )
        """
        scan_logs_ddl = """
        CREATE TABLE IF NOT EXISTS scan_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            code TEXT NOT NULL,
            staff_id TEXT NOT NULL,
            result TEXT NOT NULL,
            scanned_at TEXT NOT NULL,
            points INTEGER,
            reward_name TEXT,
            player_id TEXT,
            FOREIGN KEY(code) REFERENCES qr_codes(code)
        )
        """
    else:
        qr_codes_ddl = """
        CREATE TABLE IF NOT EXISTS qr_codes (
            code TEXT PRIMARY KEY,
            player_id TEXT NOT NULL,
            match_id TEXT,
            points INTEGER NOT NULL,
            reward_name TEXT,
            status TEXT NOT NULL DEFAULT 'issued',
            issued_at TEXT NOT NULL,
            used_at TEXT,
            used_by TEXT,
            scan_count INTEGER NOT NULL DEFAULT 0
        )
        """
        scan_logs_ddl = """
        CREATE TABLE IF NOT EXISTS scan_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL REFERENCES qr_codes(code),
            staff_id TEXT NOT NULL,
            result TEXT NOT NULL,
            scanned_at TEXT NOT NULL,
            points INTEGER,
            reward_name TEXT,
            player_id TEXT
        )
        """

    with db_transaction() as connection:
        connection.execute(text(qr_codes_ddl))
        connection.execute(text(scan_logs_ddl))
        connection.execute(text("CREATE INDEX IF NOT EXISTS idx_scan_logs_code ON scan_logs(code)"))
        connection.execute(text("CREATE INDEX IF NOT EXISTS idx_scan_logs_scanned_at ON scan_logs(scanned_at)"))


@app.on_event("startup")
def on_startup() -> None:
    initialize_database()


@app.get("/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(
        status="ok",
        database_url=engine.url.render_as_string(hide_password=True),
        database_backend=database_backend_name(),
    )


@app.post("/api/qr/issue", response_model=IssueQrResponse)
def issue_qr(request: IssueQrRequest) -> IssueQrResponse:
    code = uuid.uuid4().hex
    issued_at = now_iso()

    with db_transaction() as connection:
        connection.execute(
            text(
                """
                INSERT INTO qr_codes (
                    code,
                    player_id,
                    match_id,
                    points,
                    reward_name,
                    status,
                    issued_at,
                    used_at,
                    used_by,
                    scan_count
                ) VALUES (
                    :code,
                    :player_id,
                    :match_id,
                    :points,
                    :reward_name,
                    'issued',
                    :issued_at,
                    NULL,
                    NULL,
                    0
                )
                """
            ),
            {
                "code": code,
                "player_id": request.player_id,
                "match_id": request.match_id,
                "points": request.points,
                "reward_name": request.reward_name,
                "issued_at": issued_at,
            },
        )

    return IssueQrResponse(
        code=code,
        qr_payload=code,
        player_id=request.player_id,
        points=request.points,
        reward_name=request.reward_name,
        match_id=request.match_id,
        issued_at=issued_at,
    )


@app.post("/api/qr/issue-code", response_class=PlainTextResponse)
def issue_qr_code_plain(request: IssueQrRequest) -> str:
    issued = issue_qr(request)
    return issued.code


@app.post("/api/qr/redeem", response_model=QrResponse)
def redeem_qr(request: RedeemQrRequest) -> QrResponse:
    scanned_at = now_iso()

    with db_transaction() as connection:
        row = connection.execute(
            text("SELECT * FROM qr_codes WHERE code = :code"),
            {"code": request.code},
        ).mappings().first()

        if row is None:
            return QrResponse(
                status="invalid",
                message="Nieprawidłowy kod",
                code=request.code,
            )

        scan_count = int(row["scan_count"]) + 1
        connection.execute(
            text(
                """
                UPDATE qr_codes
                SET scan_count = :scan_count,
                    status = CASE WHEN status = 'used' THEN status ELSE 'used' END,
                    used_at = CASE WHEN used_at IS NULL THEN :used_at ELSE used_at END,
                    used_by = CASE WHEN used_by IS NULL THEN :used_by ELSE used_by END
                WHERE code = :code
                """
            ),
            {
                "scan_count": scan_count,
                "used_at": scanned_at,
                "used_by": request.staff_id,
                "code": request.code,
            },
        )

        result_status = "already_used" if row["status"] == "used" else "valid"
        message = "Kod był już skanowany" if result_status == "already_used" else f"MOŻNA WYDAĆ NAGRODĘ: {row['points']} pkt"

        connection.execute(
            text(
                """
                INSERT INTO scan_logs (
                    code,
                    staff_id,
                    result,
                    scanned_at,
                    points,
                    reward_name,
                    player_id
                ) VALUES (
                    :code,
                    :staff_id,
                    :result,
                    :scanned_at,
                    :points,
                    :reward_name,
                    :player_id
                )
                """
            ),
            {
                "code": request.code,
                "staff_id": request.staff_id,
                "result": result_status,
                "scanned_at": scanned_at,
                "points": row["points"],
                "reward_name": row["reward_name"],
                "player_id": row["player_id"],
            },
        )

    return QrResponse(
        status=result_status,
        message=message,
        code=request.code,
        player_id=row["player_id"],
        points=int(row["points"]),
        reward_name=row["reward_name"],
        match_id=row["match_id"],
        used_at=row["used_at"] or scanned_at,
        used_by=row["used_by"] or request.staff_id,
        scan_count=scan_count,
    )


@app.get("/api/qr/{code}", response_model=QrResponse)
def get_qr(code: str) -> QrResponse:
    with db_transaction() as connection:
        row = connection.execute(
            text("SELECT * FROM qr_codes WHERE code = :code"),
            {"code": code},
        ).mappings().first()

    if row is None:
        return QrResponse(status="invalid", message="Nieprawidłowy kod", code=code)

    return QrResponse(
        status=row["status"],
        message="Dane kodu QR",
        code=row["code"],
        player_id=row["player_id"],
        points=int(row["points"]),
        reward_name=row["reward_name"],
        match_id=row["match_id"],
        used_at=row["used_at"],
        used_by=row["used_by"],
        scan_count=int(row["scan_count"]),
    )


@app.get("/")
def root() -> dict[str, Any]:
    return {
        "name": "Reception QR API",
        "docs": "/docs",
        "health": "/health",
        "issue_endpoint": "/api/qr/issue",
        "redeem_endpoint": "/api/qr/redeem",
        "database_backend": database_backend_name(),
    }
